# syntax=docker/dockerfile:experimental
FROM python:3.9.7

#RUN pip install virtualenv
#ENV VIRTUAL_ENV=/venv
#RUN virtualenv venv -p python3
#ENV PATH="VIRTUAL_ENV/bin:$PATH"

WORKDIR /application
#ADD . /app

# install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . . 

# expose port
EXPOSE 5000

# run application
CMD ["python3", "-m", "run", "--host =0.0.0.0"#]